influxdb:
  image: influxdb:latest
  container_name: influxdb
  restart: always
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  env_file:
    - 'env.influxdb'

telegraf:
  image: telegraf:latest
  container_name: telegraf
  restart: always
  links:
    - influxdb
  volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  restart: always
  ports:
    - "3000:3000"
  links:
    - influxdb
